from pathlib import Path
import hashlib
import re
from page_content import home_extra, services_extra, about_extra, contact_extra, service_notes
from visual_sections import enhance

ROOT = Path(__file__).resolve().parent.parent
nav = [('index.html', 'Home'), ('services.html', 'Services'), ('about.html', 'About'), ('contact.html', 'Contact')]

def button(text='Let’s talk about your book', href='contact.html', secondary=False):
    return f'<a class="button {"secondary" if secondary else ""}" href="{href}">{text}<span aria-hidden="true">↗</span></a>'

def cards():
    items = [('01', 'Writing & editing', 'Give your ideas clarity, structure, and a voice that feels like you.', 'writing'), ('02', 'Book design', 'Thoughtful covers and beautifully considered pages, inside and out.', 'design'), ('03', 'Publishing support', 'A clear path from a finished manuscript to a book ready for readers.', 'publishing')]
    return '<div class="cards">' + ''.join(f'<a class="service-card" href="services.html#{anchor}"><span class="card-number">{n} /</span><h3>{title}</h3><p>{desc}</p><span class="text-link">Explore service <span aria-hidden="true">↗</span></span></a>' for n, title, desc, anchor in items) + '</div>'

cta = '<section class="cta container"><div><span class="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2>Let’s make something<br>worth reading.</h2></div>' + button('Start a conversation') + '</section>'

home = '''<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow"><span class="dot"></span> INK WORTH LLC · PUBLISHING & CREATIVE SERVICES</span><h1>Every story<br>deserves to<br><em>leave a mark.</em></h1><p>From the first idea to the final page. Thoughtful writing, design, and publishing support for authors and businesses.</p><div class="hero-actions">''' + button('Bring your book to life') + button('Explore our services', 'services.html', True) + '''</div><div class="hero-note"><span>YOUR WORDS.</span><span>OUR CRAFT.</span><span>SOMETHING LASTING.</span></div></div><div class="book-scene" aria-label="Decorative Ink Worth book cover designs"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="scene-label">IDEAS BECOME POSSIBILITIES.</span><div class="book book-back"><span class="book-kicker">A NEW PERSPECTIVE</span><div class="book-title">The art<br>of becoming.</div><div class="book-lines"></div><span class="book-bottom">EVERY CHAPTER IS A BEGINNING</span></div><div class="book book-front"><span class="book-kicker">A STORY ONLY YOU CAN TELL</span><div class="book-title">Make<br>your<br><i>mark.</i></div><div class="cover-rule"></div><img src="assets/brand/logo-color.png" alt="" width="87" height="80"><span class="book-bottom">INK WORTH LLC</span></div><span class="scene-caption"><span class="spark">✳</span> Great stories start with a little ink.</span></div></div></section><div class="focus-strip"><div class="container"><span>Made for your next chapter</span><span>AUTHORS</span><b>✳</b><span>ENTREPRENEURS</span><b>✳</b><span>BUSINESSES</span><b>✳</b><span>STORYTELLERS</span></div></div><section class="section container"><div class="section-heading"><div><span class="eyebrow">WHAT WE DO</span><h2>A little guidance.<br>A lasting impression.</h2></div><p>Bring us your idea, your draft, or your next big ambition. We’ll help you find the way forward.</p></div>''' + cards() + '''</section><section class="about-preview"><div class="container split"><div class="brand-panel"><img src="assets/brand/logo-dark.png" alt="Ink Worth LLC" width="270" height="249"><span>WORDS WITH PURPOSE. BOOKS WITH PERSONALITY.</span></div><div><span class="eyebrow">THE PEOPLE BEHIND THE PAGES</span><h2>Your story.<br>Thoughtfully brought to life.</h2><p>Ink Worth is built around a simple belief: meaningful ideas deserve thoughtful execution. We bring words, design, and publishing together with care for the details that make your work yours.</p><a class="text-link" href="about.html">Get to know Ink Worth <span aria-hidden="true">↗</span></a></div></div></section>''' + cta

services = '''<section class="page-intro container"><span class="eyebrow">OUR SERVICES</span><h1>Good ideas.<br><em>Beautifully realised.</em></h1><p>Support for every stage of your book. Choose the help you need, wherever you are in the process.</p></section><section class="container service-details">'''
for number, anchor, title, desc, bullets in [
    ('01', 'writing', 'Writing & editing', 'Shape your ideas into words that connect. We help you build a clear narrative while keeping your voice at the heart of the work.', ['Manuscript development and structure', 'Copyediting and proofreading', 'Business and brand storytelling']),
    ('02', 'design', 'Book design', 'Create a first impression that belongs to your story, with a reading experience that is just as considered.', ['Book cover concepts and design', 'Interior layout and typesetting', 'Print and digital file preparation']),
    ('03', 'publishing', 'Publishing support', 'Make the next steps feel manageable. We help you understand what your book needs to move from manuscript to publication.', ['Publication planning and guidance', 'Print and ebook preparation', 'Launch materials and creative support'])]:
    notes = '<div class="service-notes">'+''.join(f'<div><h3>{t}</h3><p>{d}</p></div>' for t,d in service_notes[anchor])+'</div>'
    services += f'<article class="service-detail" id="{anchor}"><span class="detail-number">{number}</span><div><h2>{title}</h2><p>{desc}</p><ul class="check-list">'+''.join(f'<li>{b}</li>' for b in bullets)+'</ul>'+notes+'</div>'+button('Discuss your project', 'contact.html?service='+anchor, True)+'</article>'
services += '</section><section class="process section"><div class="container"><span class="eyebrow">HOW WE WORK</span><h2>A clear path, from day one.</h2><div class="cards">'+''.join(f'<div><span class="card-number">0{i+1} /</span><h3>{t}</h3><p>{d}</p></div>' for i,(t,d) in enumerate([('First, we listen.', 'Tell us about your idea, your audience, and what you want to achieve.'), ('Then, we make a plan.', 'We agree on the scope, deliverables, and timeline before work begins.'), ('Together, we refine.', 'We keep you involved as the work takes shape, with space for your feedback.')]))+'</div></div></section>'+cta

about = '''<section class="page-intro container"><span class="eyebrow">ABOUT INK WORTH</span><h1>We believe in<br><em>the worth of words.</em></h1><p>Stories move people. Ideas build businesses. The right words can leave an impression long after the last page.</p></section><section class="about-preview"><div class="container split"><div class="brand-panel"><img src="assets/brand/logo-dark.png" alt="Ink Worth LLC" width="270" height="249"><span>A LITTLE INK. A LASTING IMPACT.</span></div><div><span class="eyebrow">OUR APPROACH</span><h2>Care in every chapter.</h2><p>Ink Worth LLC brings writing, design, and publishing support together for authors and businesses ready to turn an idea into something tangible.</p><p>We approach each project as a collaboration. That means listening first, asking the right questions, and treating your story with the attention it deserves.</p>''' + button('Explore our services','services.html')+'''</div></div></section><section class="section container"><span class="eyebrow">WHAT MATTERS TO US</span><h2>The details make the difference.</h2><div class="cards"><div class="value-card"><span class="card-number">01 /</span><h3>Your voice, always.</h3><p>Your perspective is what makes your work distinctive. Our role is to help it come through clearly.</p></div><div class="value-card"><span class="card-number">02 /</span><h3>Purposeful craft.</h3><p>Every word, layout, and design choice should serve your story and the people reading it.</p></div><div class="value-card"><span class="card-number">03 /</span><h3>Real collaboration.</h3><p>Clear conversations, a shared direction, and thoughtful feedback throughout the process.</p></div></div></section>'''+cta

contact = '''<section class="page-intro container"><span class="eyebrow">LET’S CONNECT</span><h1>Your next chapter<br><em>starts with a hello.</em></h1><p>A new idea, a manuscript in progress, or a business story to tell. We’d love to hear what you have in mind.</p></section><section class="container contact-grid"><aside><h2>Tell us your story.</h2><p>You don’t need to have every detail figured out. Start with what you know, and we’ll take it from there.</p><div class="contact-note"><span class="eyebrow">HELPFUL THINGS TO INCLUDE</span><ul class="check-list"><li>What you’re working on</li><li>The support you’re looking for</li><li>Your ideal timeline</li></ul></div><img class="contact-logo" src="assets/brand/logo-color.png" alt="Ink Worth LLC" width="150" height="138"></aside><form id="enquiry-form"><div class="form-row"><label>Your name <span>*</span><input name="name" autocomplete="name" required maxlength="100" placeholder="Full name"></label><label>Email address <span>*</span><input name="email" type="email" autocomplete="email" required maxlength="254" placeholder="you@example.com"></label></div><label>Company or book title<input name="company" maxlength="200" placeholder="Optional"></label><label>What can we help with? <span>*</span><select name="service" required><option value="">Select a service</option><option value="writing">Writing & editing</option><option value="design">Book design</option><option value="publishing">Publishing support</option><option value="other">A little of everything / Not sure yet</option></select></label><label>Tell us about your project <span>*</span><textarea name="message" required rows="5" maxlength="5000" placeholder="Your idea, where you are in the process, and what you have in mind…"></textarea></label><p class="form-hint" id="form-hint">Create a project brief to save your enquiry. Nothing is sent automatically.</p><button type="submit" class="button" id="submit-enquiry">Save project brief <span aria-hidden="true">↗</span></button><p id="form-status" role="status" tabindex="-1"></p></form></section>'''

home = home.removesuffix(cta) + home_extra + cta
services = services.removesuffix(cta) + services_extra + cta
about = about.removesuffix(cta) + about_extra + cta
contact += contact_extra
home, services, about, contact = enhance(home, services, about, contact)

for filename, title in nav:
    content = {'Home':home,'Services':services,'About':about,'Contact':contact}[title]
    links = ''.join(f'<a href="{f}"'+(' aria-current="page"' if f==filename else '')+f'>{t}</a>' for f,t in nav)
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#050415"><title>{'Ink Worth LLC | Every story deserves to leave a mark' if title=='Home' else title+' | Ink Worth LLC'}</title><meta name="description" content="Ink Worth LLC — thoughtful writing, book design, and publishing support for authors and businesses."><link rel="icon" type="image/png" href="assets/brand/favicon.png"><link rel="stylesheet" href="assets/site.css"><script src="assets/site.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container header-inner"><a class="logo" href="index.html" aria-label="Ink Worth LLC home"><img src="assets/brand/logo-dark.png" alt="Ink Worth LLC" width="88" height="81"></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">☰</span></button><nav id="main-nav" aria-label="Main navigation">{links}</nav><a class="button header-cta" href="contact.html">Let’s talk <span aria-hidden="true">↗</span></a></div></header><main id="main">{content}</main><footer><div class="container footer-top"><a href="index.html" aria-label="Ink Worth LLC home"><img src="assets/brand/logo-light.png" width="108" height="100" alt="Ink Worth LLC"></a><p>Thoughtful words.<br>Beautiful books. Lasting impressions.</p><nav aria-label="Footer navigation">{links}</nav></div><div class="container footer-bottom"><span>© {2026} Ink Worth LLC. All rights reserved.</span><span>Every story deserves to leave a mark.</span></div></footer></body></html>'''
    html = html.replace('</head>', '<link rel="stylesheet" href="assets/details.css"><link rel="stylesheet" href="assets/photography.css"></head>')
    if title == 'Services':
        html = html.replace('</head>', '<link rel="stylesheet" href="assets/service-scroll.css"><script src="assets/service-scroll.js" defer></script></head>')
    # Asset URLs change with their contents, so older browser caches cannot
    # retain a previous header or scrolling implementation after a page reload.
    def version_asset(match):
        path = match.group(2)
        version = hashlib.sha256((ROOT/path).read_bytes()).hexdigest()[:12]
        return f'{match.group(1)}{path}?v={version}{match.group(3)}'
    html = re.sub(r'((?:href|src)=")(assets/[^"?]+\.(?:css|js))(")', version_asset, html)
    (ROOT/filename).write_text(html, encoding='utf-8')
print('Built four Ink Worth business pages.')
