def heading(kicker, title, description=''):
    return f'<div class="section-heading"><div><span class="eyebrow">{kicker}</span><h2>{title}</h2></div>' + (f'<p>{description}</p>' if description else '') + '</div>'

def faq(items, title='A few questions, answered.'):
    return '<section class="section container faq-section">'+heading('GOOD TO KNOW', title)+'<div class="faq-list">'+''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>{a}</p></div></details>' for q,a in items)+'</div></section>'

journey = '''<section class="journey section"><div class="container">'''+heading('FROM FIRST THOUGHT TO FINAL PAGE', 'Your vision. A thoughtful process.', 'Each project has its own starting point. We build the next steps around yours.')+'''<div class="journey-grid">'''+''.join(f'<article class="journey-step"><span class="step-index">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>' for i,(t,d) in enumerate([
('Discover the story', 'We begin with your purpose, audience, and ambitions. Share your manuscript, outline, or idea so we can understand the work ahead.'),
('Shape the direction', 'Together, we define the scope: the services you need, the materials to prepare, and the milestones that will guide the project.'),
('Create & refine', 'Words and design come together through considered drafts and feedback. You help steer the details that make the project feel like yours.'),
('Prepare the next chapter', 'We review the agreed deliverables and prepare the final materials, with clear guidance on how to use them and what comes next.')]))+'''</div></div></section>'''

audiences = '''<section class="section container">'''+heading('WHO WE WORK WITH', 'Different ambitions.<br>The same attention to detail.', 'A personal story, a professional perspective, or a publication with a business purpose. There is room for all three.')+'''<div class="audience-grid">'''+''.join(f'<article class="audience-card"><span class="eyebrow">{k}</span><h3>{t}</h3><p>{d}</p><ul class="check-list">'+''.join(f'<li>{x}</li>' for x in points)+'</ul></article>' for k,t,d,points in [
('THE PERSONAL CHAPTER','Authors & storytellers','Turn the story you have been carrying into a reading experience that feels complete.', ['Fiction and personal narratives','Memoirs and reflective writing','First manuscripts and revised drafts']),
('THE PROFESSIONAL CHAPTER','Experts & entrepreneurs','Give your knowledge a clear structure and turn your experience into a useful resource.', ['Business and thought leadership books','Practical guides and workbooks','Educational and specialist content']),
('THE BUSINESS CHAPTER','Brands & organisations','Create publications that express your identity and make complex ideas easier to understand.', ['Company stories and brand publications','Customer guides and editorial content','Internal resources and training materials'])])+'''</div></section>'''

showcase = '''<section class="showcase section"><div class="container">'''+heading('POSSIBILITIES IN PRINT', 'One idea.<br>So many ways to tell it.', 'Illustrative formats to spark a direction for your project.')+'''<div class="format-grid"><article><div class="format-art art-story" aria-hidden="true"><div class="mini-cover"><small>A PERSONAL JOURNEY</small><strong>Between<br>the <i>lines.</i></strong><span>STORIES THAT STAY WITH US</span></div></div><h3>The story that stays.</h3><p>A memoir or novel shaped around voice, rhythm, and an immersive reading experience.</p></article><article><div class="format-art art-guide" aria-hidden="true"><div class="mini-cover"><small>IDEAS INTO ACTION</small><strong>A different<br>kind of<br><i>thinking.</i></strong><span>A PRACTICAL PERSPECTIVE</span></div></div><h3>The idea that leads.</h3><p>A business book or expert guide that makes your perspective clear and your knowledge useful.</p></article><article><div class="format-art art-workbook" aria-hidden="true"><div class="mini-cover"><small>SPACE TO EXPLORE</small><strong>Make<br>room for<br><i>more.</i></strong><span>NOTES · IDEAS · POSSIBILITIES</span></div></div><h3>The page that inspires.</h3><p>A workbook or branded publication designed to invite participation, reflection, and discovery.</p></article></div><p class="sample-note">Concept designs shown for illustration; these are not client projects.</p></div></section>'''

home_faq = faq([
('I only have an idea. Can I still get started?', 'Yes. A short outline, a few notes, or a description of your audience is a useful starting point. The first step is to clarify what you want to create and identify the support that would help you move forward.'),
('Can I choose just one service?', 'You can discuss a focused piece of work, such as editing an existing draft or designing a cover, as well as support across several stages. The scope is agreed around your project.'),
('What affects the timeline and cost?', 'Manuscript length, its current condition, design complexity, required formats, and the amount of revision all affect the scope. Share these details and any target date so the work can be planned realistically.'),
('Do you work on business publications as well as books?', 'The same care for words and design applies to business guides, workbooks, brand stories, and educational materials. Tell us the purpose and who will read it so we can discuss the right approach.')])

home_extra = audiences + journey + showcase + '''<section class="editorial-band"><div class="container split"><span class="large-quote" aria-hidden="true">“</span><div><span class="eyebrow">THE INK WORTH PHILOSOPHY</span><h2>The best version of your story<br>still sounds like you.</h2><p>Our role is to bring clarity to your words and intention to your design. From a small editorial detail to the feeling of a finished cover, every decision should help your idea connect with its reader.</p><a class="text-link" href="about.html">Discover our approach <span aria-hidden="true">↗</span></a></div></div></section>''' + home_faq

service_notes = {
'writing': [('Where we begin', 'Share your manuscript or a representative sample, its approximate word count, and the audience you want to reach. Let us know whether you need help with the overall structure, sentence-level clarity, or a final proofread.'), ('What we work on', 'Depending on the agreed scope, we can address organisation, consistency, flow, tone, grammar, and readability. Structural editing and final proofreading serve different purposes; we clarify the level of attention your draft needs.'), ('What you take forward', 'The agreed edited material and editorial guidance give you a clearer next draft. Revision rounds, file formats, and the boundaries of the edit are defined before work starts.')],
'design': [('Where we begin', 'Your manuscript, intended format, audience, and visual references establish the direction. If you have brand guidelines or a preferred printing platform, include those requirements in the brief.'), ('What we work on', 'Cover concepts establish the visual tone while interior design considers hierarchy, typography, spacing, and page flow. The format and reading experience guide the design rather than decoration alone.'), ('What you take forward', 'Final design files are prepared to the formats and specifications agreed for the project. Print layouts, ebook requirements, and editable source files are discussed individually so the handover is clear.')],
'publishing': [('Where we begin', 'We review where your project stands, the formats you are considering, and your intended route to readers. A finished manuscript and a target publication date help identify the remaining preparation.'), ('What we work on', 'Support can include a publication checklist, file preparation, and launch materials. Platform choices, production requirements, and the sequence of tasks are considered as part of your plan.'), ('What you take forward', 'You receive the agreed prepared materials and a practical outline of next steps. Printing, platform accounts, distribution arrangements, and third-party charges are scoped separately when relevant.')]
}

services_extra = '''<section class="section container">'''+heading('BUILD THE RIGHT BRIEF', 'Choose your starting point.', 'You do not need every service. Start with the stage that matches your project today.')+'''<div class="comparison-wrap"><table><caption>Support by project stage</caption><thead><tr><th scope="col">Where you are</th><th scope="col">A useful next step</th><th scope="col">What to bring</th></tr></thead><tbody><tr><th scope="row">An idea or early outline</th><td>Writing and structure guidance</td><td>Your concept, audience, and key messages</td></tr><tr><th scope="row">A complete draft</th><td>Editorial review and refinement</td><td>Your manuscript and approximate word count</td></tr><tr><th scope="row">A polished manuscript</th><td>Cover design and interior layout</td><td>The edited text, format, and design references</td></tr><tr><th scope="row">Ready for publication</th><td>File preparation and publishing guidance</td><td>Final materials and platform requirements</td></tr></tbody></table></div></section>'''+faq([
('How is a project scoped?', 'The scope describes the work, deliverables, review stages, and responsibilities. It should also identify anything outside the project, such as printing fees or additional formats, before work begins.'),
('Are revisions included?', 'The number and type of review rounds are agreed for each project. Feedback works best when it is gathered into a clear set of comments at each milestone. New requirements may change the scope.'),
('Can you work with an existing cover or brand identity?', 'Share the original files, usage permissions, brand guidelines, and the changes you need. These help establish whether existing materials can be adapted or whether a new design is appropriate.'),
('Does publishing support guarantee sales or distribution?', 'No. Preparing a publication does not guarantee platform acceptance, retail placement, or sales. Those outcomes depend on external requirements, distribution decisions, marketing, and reader demand.')], 'Before we begin.')

about_extra = '''<section class="editorial-band"><div class="container split"><div><span class="eyebrow">WHY INK WORTH</span><h2>Because the story<br>is only the beginning.</h2></div><div><p>An idea has potential. Bringing it to a reader takes another kind of care: finding the structure, sharpening the language, and creating a design that makes the content inviting.</p><p>We bring these disciplines into one conversation. Editorial choices inform the layout. The audience shapes the cover. The intended format guides how the final materials are prepared.</p><p>The aim is a coherent publication, with each part working toward the same purpose.</p></div></div></section>'''+'''<section class="section container">'''+heading('WHAT COLLABORATION LOOKS LIKE', 'A shared direction.<br>Room for your perspective.')+'''<div class="principle-grid">'''+''.join(f'<article><span class="card-number">0{i+1} /</span><h3>{t}</h3><p>{d}</p></article>' for i,(t,d) in enumerate([
('Listening before creating', 'Your goals, references, and concerns form the starting point. We want to understand what success means for this particular project before proposing a direction.'),
('Making decisions clear', 'A useful recommendation explains its purpose. We connect choices about language, structure, and design to your intended audience and reading experience.'),
('Feedback with a purpose', 'Review stages create space to ask questions and refine the work. A shared brief helps keep feedback focused while allowing the strongest ideas to develop.'),
('A considered handover', 'The final stage is about usability as well as appearance. Agreed files, formats, and next steps should be understandable when the project moves into your hands.')]))+'''</div></section>'''+audiences+'''<section class="mission-note container"><span class="eyebrow">OUR GUIDING IDEA</span><h2>Words carry your perspective.<br>Design helps the world see it.</h2><p>We believe a successful collaboration respects both. That is the thinking we bring to every Ink Worth project.</p></section>'''

contact_extra = '''<section class="process section"><div class="container">'''+heading('MAKE A USEFUL FIRST BRIEF', 'A little context goes a long way.', 'Share what you know. Leave room for the questions we can work through together.')+'''<div class="cards">'''+''.join(f'<article><span class="card-number">0{i+1} /</span><h3>{t}</h3><p>{d}</p></article>' for i,(t,d) in enumerate([
('Your project', 'Describe what you are making, who it is for, and what you want readers to take away. Mention whether you have an idea, outline, first draft, or finished manuscript.'),
('Your priorities', 'Tell us where you most need help: the words, the design, or the next steps toward publication. Include an approximate word count and any required formats.'),
('Your practical details', 'Add a target date, a budget range if you have one, and anything that is already fixed. If you have visual references or brand guidelines, mention them in your message.')]))+'''</div></div></section>'''+faq([
('Do I need a finished manuscript to make an enquiry?', 'No. Describe your idea and its current stage. An early conversation can focus on structure and direction, while a completed manuscript makes it easier to discuss editing or design requirements.'),
('Should I include my whole manuscript in the form?', 'A short description is enough for the initial brief. Include the genre or topic, approximate length, and the kind of support you need. There is no manuscript upload on this form.'),
('What if I am unsure which service to choose?', 'Select “A little of everything / Not sure yet” and describe what you want to achieve. Your current materials and priorities will help determine the most useful starting point.'),
('What happens when I prepare an email enquiry?', 'The form opens your email app with your project details addressed to contact@inkworthllc.com. Review the message and send it from your email app. You can also email us directly or call (321) 332-0682.'),
('Can I include a deadline or budget?', 'Yes. Include these in your project description. They help frame a realistic scope; sending an enquiry does not confirm availability, pricing, or a delivery date.')], 'Before you reach out.')
